version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 8000:3306

