# Generated by Django 2.2.4 on 2019-11-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0005_auto_20191130_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticimage',
            name='image',
            field=models.ImageField(upload_to='images/cosmetics'),
        ),
    ]
