# Generated by Django 2.2.4 on 2019-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0007_comment_cosmetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/cosmetics'),
            preserve_default=False,
        ),
    ]
