# Generated by Django 2.2.4 on 2019-11-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic', '0008_cosmetic_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
